services:
 
  db:
    image: postgres:15-alpine
    container_name: postgresFirstDemo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ambrella3443
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

 
  app:
    build: .
    container_name: reservation_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ambrella3443

volumes:
  pgdata: